import { BasicFieldType } from "@/types/resume";
import { CardTemplate } from "@/types/template";

// 预设宽高比配置
export const ASPECT_RATIOS = [
  { id: "1:1", name: "1:1 正方形", ratio: 1, width: 400, height: 400 },
  { id: "3:4", name: "3:4 小红书", ratio: 3 / 4, width: 360, height: 480 },
  { id: "4:3", name: "4:3 Instagram", ratio: 4 / 3, width: 480, height: 360 },
  { id: "7:5", name: "7:5 Pinterest", ratio: 7 / 5, width: 420, height: 300 },
  { id: "9:16", name: "9:16 TikTok", ratio: 9 / 16, width: 270, height: 480 },
  { id: "16:9", name: "16:9 YouTube", ratio: 16 / 9, width: 480, height: 270 },
  { id: "210:297", name: "210:297 A4", ratio: 210 / 297, width: 350, height: 495 },
  { id: "custom", name: "自定义", ratio: 0, width: 440, height: 0 }
] as const;

export const DEFAULT_FIELD_ORDER: BasicFieldType[] = [
  { id: "1", key: "name", label: "姓名", type: "text", visible: true },

  { id: "2", key: "title", label: "职位", type: "text", visible: true },
  {
    id: "3",
    key: "employementStatus",
    label: "状态",
    type: "text",
    visible: true
  },
  { id: "4", key: "birthDate", label: "生日", type: "date", visible: true },
  { id: "5", key: "email", label: "邮箱", type: "text", visible: true },
  { id: "6", key: "phone", label: "电话", type: "text", visible: true },
  { id: "7", key: "location", label: "所在地", type: "text", visible: true }
];

export const DEFAULT_TEMPLATES: CardTemplate[] = [
  {
    id: "default",
    name: "默认",
    description: "简洁大方的默认卡片样式，适合各种内容展示",
    thumbnail: "default",
    defaultForm: {
      icon: "🚲",
      date: "2025年10月12日",
      title: "👋 hi 你好",
      content: "Product managers must have the ability to perceive human nature and business. Only in this way can they better identify market pain points, understand user needs, and use business to refine product ideas, instead of merely being an employee to implement the company's designated product roadmap.",
      author: "Ant Card",
      textCount: "Word count:",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 295
    },
    defaultStyle: {
      align: "left",
      backgroundName: "default-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "8px",
      color: "#212529",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "transparent",
    name: "透明",
    description: "透明背景设计，营造轻盈视觉效果",
    thumbnail: "transparent",
    defaultForm: {
      icon: "",
      date: "2025年10月12日",
      title: "透明卡片",
      content: "透明背景设计，营造轻盈的视觉效果，让内容更加突出。",
      author: "作者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 45
    },
    defaultStyle: {
      align: "left",
      backgroundName: "transparent-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "16px",
      color: "#374151",
      opacity: 1,
      blur: 10,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "rgba(248, 250, 252, 0.95)",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "quote",
    name: "金句",
    description: "引人注目的引述卡片设计，突出名言金句",
    thumbnail: "quote",
    defaultForm: {
      icon: "❝",
      date: "2025年10月12日",
      title: "每日金句",
      content: "生活就像骑自行车，想保持平衡就得往前走。",
      author: "阿尔伯特·爱因斯坦",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 21
    },
    defaultStyle: {
      align: "center",
      backgroundName: "quote-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.2,
      padding: "40px",
      borderRadius: "24px",
      color: "#1a202c",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)",
      containerRotate: -2,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.5px" },
      rowSpacings: { content: "16px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "book-excerpt",
    name: "书摘",
    description: "仿古书籍摘录设计，带有页边距和装订线效果",
    thumbnail: "book-excerpt",
    defaultForm: {
      icon: "📚",
      date: "2025年10月12日",
      title: "文学摘录",
      content: "读书是在别人思想的帮助下，建立起自己的思想。\n\n——鲁巴金",
      author: "摘录者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 28
    },
    defaultStyle: {
      align: "left",
      backgroundName: "book-excerpt-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Songti SC, serif",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1.1,
      padding: "40px 30px 40px 50px",
      borderRadius: "0px",
      color: "#333333",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f9f4e8",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.8px" },
      rowSpacings: { content: "12px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "memo",
    name: "备忘录",
    description: "模仿iPhone备忘录设计，带有顶部导航栏和黄色主题",
    thumbnail: "memo",
    defaultForm: {
      icon: "📝",
      date: "2025年10月12日",
      title: "购物清单",
      content: "• 牛奶\n• 面包\n• 鸡蛋\n• 苹果\n• 洗发水",
      author: "备忘录",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 25
    },
    defaultStyle: {
      align: "left",
      backgroundName: "memo-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "0px",
      borderRadius: "12px",
      color: "#713f12",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fef3c7",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: false,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "bento",
    name: "便当",
    description: "真正的网格布局便当设计，信息分块展示",
    thumbnail: "bento",
    defaultForm: {
      icon: "🍱",
      date: "2025年10月12日",
      title: "信息便当",
      content: "## 今日要点\n- 项目进度更新\n- 团队会议安排\n- 客户反馈整理\n\n## 待办事项\n- [ ] 完成报告\n- [ ] 回复邮件\n- [ ] 准备演示",
      author: "便当师傅",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 45
    },
    defaultStyle: {
      align: "left",
      backgroundName: "bento-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "20px",
      borderRadius: "12px",
      color: "#1e293b",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f8fafc",
      containerRotate: 0,
      lineHeights: { content: "1.5" },
      letterSpacings: { content: "0.2px" },
      rowSpacings: { content: "8px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: false,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "dark-day",
    name: "黑日",
    description: "星空夜景设计，带有星光点缀效果",
    thumbnail: "dark-day",
    defaultForm: {
      icon: "✨",
      date: "2025年10月12日",
      title: "夜的诗篇",
      content: "夜空中的每一颗星，都是宇宙写给地球的情书。\n\n在这静谧的夜晚，让我们聆听内心的声音。",
      author: "观星者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 38
    },
    defaultStyle: {
      align: "center",
      backgroundName: "dark-day-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "9:16",
      height: 0,
      fontScale: 1.1,
      padding: "40px",
      borderRadius: "24px",
      color: "#f1f5f9",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.3px" },
      rowSpacings: { content: "16px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "frame",
    name: "框届",
    description: "艺术画框装饰设计，突出内容如艺术品般展示",
    thumbnail: "frame",
    defaultForm: {
      icon: "🎨",
      date: "2025年10月12日",
      title: "艺术之作",
      content: "每一个想法都是一件艺术品，\n每一句话都值得被精心装裱。\n\n在这个数字世界里，\n让文字回归艺术的本质。",
      author: "艺术家",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 42
    },
    defaultStyle: {
      align: "center",
      backgroundName: "frame-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "KaiTi, cursive",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.1,
      padding: "50px 40px 50px 40px",
      borderRadius: "0px",
      color: "#2d3748",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fefefe",
      containerRotate: 0,
      lineHeights: { content: "2.0" },
      letterSpacings: { content: "1px" },
      rowSpacings: { content: "20px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "minimal",
    name: "简约",
    description: "极简主义设计，突出内容本质",
    thumbnail: "minimal",
    defaultForm: {
      icon: "",
      date: "2025年10月12日",
      title: "简约之美",
      content: "少即是多，简约不是简单，而是去除多余，保留精华。",
      author: "极简主义者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 28
    },
    defaultStyle: {
      align: "left",
      backgroundName: "minimal-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "40px",
      borderRadius: "4px",
      color: "#262626",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: false,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "story",
    name: "故事",
    description: "叙事风格设计，适合故事内容展示",
    thumbnail: "story",
    defaultForm: {
      icon: "📚",
      date: "2025年10月12日",
      title: "故事开始",
      content: "每个人都有自己的故事，每个故事都值得被倾听和记录。让我们一起分享这些美好的时光。",
      author: "故事讲述者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 44
    },
    defaultStyle: {
      align: "left",
      backgroundName: "story-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "36px",
      borderRadius: "12px",
      color: "#134e4a",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f0fdfa",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: true,
      showWatermark: true
    }
  },
  {
    id: "handwritten",
    name: "手写",
    description: "手写风格设计，温馨个性化展示",
    thumbnail: "handwritten",
    defaultForm: {
      icon: "✍️",
      date: "2025年10月12日",
      title: "手写心情",
      content: "用心书写的文字总是带着温度，就像手写的信件一样，传递着真挚的情感。\n\n这是一段手写风格的文本示例，展现了手写模板的独特魅力。每一个字都仿佛带着书写者的温度，让阅读变得更加温暖和亲切。",
      author: "手写爱好者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 65
    },
    defaultStyle: {
      align: "left",
      backgroundName: "handwritten-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "'Kalam', cursive",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1.1,
      padding: "32px",
      borderRadius: "16px",
      color: "#831843",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)",
      containerRotate: 1,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "code",
    name: "代码",
    description: "代码风格设计，适合技术内容展示",
    thumbnail: "code",
    defaultForm: {
      icon: "💻",
      date: "2025年10月12日",
      title: "代码人生",
      content: "// 人生就像写代码\n// 需要不断调试和优化\nconsole.log('Hello, World!');",
      author: "程序员",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 45
    },
    defaultStyle: {
      align: "left",
      backgroundName: "code-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "JetBrains Mono",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 0.9,
      padding: "24px",
      borderRadius: "8px",
      color: "#0f172a",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f8fafc",
      containerRotate: 0,
      lineHeights: { content: "1.4" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "image",
    name: "图片",
    description: "图片展示优化设计，突出视觉内容",
    thumbnail: "image",
    defaultForm: {
      icon: "🖼️",
      date: "2025年10月12日",
      title: "视觉盛宴",
      content: "一图胜千言，好的视觉设计能够瞬间传达信息，触动人心。",
      author: "视觉设计师",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 30
    },
    defaultStyle: {
      align: "left",
      backgroundName: "image-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "12px",
      color: "#9a3412",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fff7ed",
      containerRotate: 0,
      lineHeights: { content: "" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "document",
    name: "文档",
    description: "简洁的白底 + 柔和阴影，给人「轻量」「清爽」「纸质笔记」的感觉",
    thumbnail: "document",
    defaultForm: {
      icon: "📄",
      date: "2025年10月12日",
      title: "文档标题",
      content: "## 二级标题\n\n这是文档内容区域，您可以在这里编写详细的内容。段落之间有充足的留白，让阅读体验更加舒适。\n\n### 三级标题\n\n- 列表项一\n- 列表项二\n- 列表项三\n\n```javascript\n// 示例代码\nconsole.log('Hello, World!');\n```\n\n> 这是一个引用区块，用于突出显示重要内容。",
      author: "作者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 85
    },
    defaultStyle: {
      align: "left",
      backgroundName: "document-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "40px",
      borderRadius: "8px",
      color: "#2d3748",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "1.7" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "12px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "vertical",
    name: "竖排",
    description: "传统竖排文字设计，展现古典韵味",
    thumbnail: "vertical",
    defaultForm: {
      icon: "🎋",
      date: "2025年10月12日",
      title: "竖排文字",
      content: "这里是竖排文字内容。竖排排版在中国传统文化中有着悠久的历史，给人一种古典、优雅的感觉。",
      author: "作者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 100
    },
    defaultStyle: {
      align: "left",
      backgroundName: "vertical-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "0px",
      color: "#44403c",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fdfbf7",
      containerRotate: 0,
      lineHeights: { content: "2" },
      letterSpacings: { content: "0.1em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "gradient",
    name: "渐变",
    description: "现代渐变风格，搭配玻璃拟态效果",
    thumbnail: "gradient",
    defaultForm: {
      icon: "🌈",
      date: "2025年10月12日",
      title: "渐变风格",
      content: "渐变色彩能带来丰富的视觉体验，配合玻璃拟态效果，让卡片看起来更加现代和通透。",
      author: "作者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 80
    },
    defaultStyle: {
      align: "left",
      backgroundName: "gradient-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "24px",
      borderRadius: "16px",
      color: "#ffffff",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "transparent",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "elegant-dark",
    name: "暗夜",
    description: "深色背景搭配衬线字体，尽显高端优雅",
    thumbnail: "elegant-dark",
    defaultForm: {
      icon: "🌙",
      date: "2025年10月12日",
      title: "暗夜优雅",
      content: "深色背景搭配衬线字体，营造出一种静谧、高端的阅读氛围。适合展示诗歌、散文或深度的思考内容。",
      author: "作者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 120
    },
    defaultStyle: {
      align: "center",
      backgroundName: "elegant-dark-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "40px",
      borderRadius: "0px",
      color: "#e5e5e5",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#1a1a1a",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.05em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "cyberpunk",
    name: "赛博朋克",
    description: "霓虹光效与代码风格，充满未来科技感",
    thumbnail: "cyberpunk",
    defaultForm: {
      icon: "⚡",
      date: "2077-10-12",
      title: "SYSTEM_OVERRIDE",
      content: "Wake up, Samurai. We have a city to burn. The digital frontier is not just a place, it's a state of mind.",
      author: "V",
      textCount: "BYTES",
      qrCodeTitle: "NET_LINK",
      qrCodeText: "SCAN_TO_CONNECT",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 1024
    },
    defaultStyle: {
      align: "left",
      backgroundName: "cyberpunk-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "JetBrains Mono",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "24px",
      borderRadius: "0px",
      color: "#22d3ee",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#050505",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "0.05em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "bold-typography",
    name: "醒目",
    description: "超大字号排版，强调核心观点",
    thumbnail: "bold-typography",
    defaultForm: {
      icon: "✦",
      date: "2025.10.12",
      title: "BOLD VISION",
      content: "Simplicity is the ultimate sophistication. Focus on what matters.",
      author: "Steve",
      textCount: "WORDS",
      qrCodeTitle: "Ant Card",
      qrCodeText: "Scan Me",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 12
    },
    defaultStyle: {
      align: "left",
      backgroundName: "bold-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Inter",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.2,
      padding: "32px",
      borderRadius: "0px",
      color: "#000000",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "1.4" },
      letterSpacings: { content: "-0.02em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "social-post",
    name: "社交动态",
    description: "模拟社交媒体动态卡片，适合分享短内容",
    thumbnail: "social-post",
    defaultForm: {
      icon: "🚀",
      date: "2 hrs ago",
      title: "New Update Available",
      content: "We just released a major update to our platform. Check out the new features including dark mode, improved performance, and more!",
      author: "Ant Design",
      textCount: "CHARS",
      qrCodeTitle: "Ant Card",
      qrCodeText: "Install Now",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 140
    },
    defaultStyle: {
      align: "left",
      backgroundName: "social-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Inter",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "24px",
      borderRadius: "24px",
      color: "#1f2937",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f3f4f6",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "tech-doc",
    name: "技术文档",
    description: "清爽的技术文档风格，适合代码分享和教程",
    thumbnail: "tech-doc",
    defaultForm: {
      icon: "🤖",
      date: "2025年8月25日",
      title: "如何充分发挥GPT-5的打码能力",
      content: "GPT-5 for Coding\n\n尽管功能强大，但使用GPT-5进行提示与其他模型可能有所不同。以下是通过API或在你的编码工具中充分利用它的技巧。\n\n1. **提供上下文**：GPT-5需要了解你的项目结构。\n2. **明确指令**：告诉它你想要什么，而不是不想要什么。\n3. **迭代优化**：不要期望一次完美，通过对话完善代码。",
      author: "官方发布",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫码阅读全文",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 300
    },
    defaultStyle: {
      align: "left",
      backgroundName: "tech-doc-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Inter",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "24px",
      borderRadius: "12px",
      color: "#334155",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f0f4f8",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "feature-cover",
    name: "封面故事",
    description: "大图封面设计，适合文章推送和故事分享",
    thumbnail: "feature-cover",
    defaultForm: {
      icon: "🌊",
      date: "2025年8月21日",
      title: "故事模板第一个布局隐藏头像、作者、签名、水印、页码和二维码",
      content: "本文字段左边有一个竖线条，这是引用样式，只需要在段首输入一个大于号加一个空格即可设置成引用的样式。\n\n生活就像一盒巧克力，你永远不知道下一颗是什么味道。",
      author: "Ant Card",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 50
    },
    defaultStyle: {
      align: "left",
      backgroundName: "feature-cover-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "24px",
      borderRadius: "16px",
      color: "#1f2937",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f3f4f6",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "neon-glow",
    name: "霓虹微光",
    description: "暗色背景下的微光效果，聚焦核心内容",
    thumbnail: "neon-glow",
    defaultForm: {
      icon: "✨",
      date: "2025.08.25",
      title: "Neon Thoughts",
      content: "和 claude code 改了屎山，最后用这个提示词拯救了我：\n\n调用相关 agents 分析思考找到原因，或者考虑重构代码，我们可能把一些东西复杂化了，思考一下",
      author: "魔王哒",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "Scan Me",
      pagination: "80",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 80
    },
    defaultStyle: {
      align: "center",
      backgroundName: "neon-glow-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.1,
      padding: "32px",
      borderRadius: "16px",
      color: "#e5e7eb",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#0f1115",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "0.02em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: false,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "highlight-memo",
    name: "高光笔记",
    description: "模拟荧光笔高光效果，重点突出，清晰明了",
    thumbnail: "highlight-memo",
    defaultForm: {
      icon: "📝",
      date: "2025年8月17日",
      title: "250803本周回顾",
      content: "**本周我最大的改变：**\n\n1. **重新拿回了生活的掌控感。**\n\n因为小王出差了，所以我开始做选择。\n\n比如买什么菜，中午要不要出去吃饭，几点出门上班，走哪条路上班等等。\n\n惊讶地发现，我感受到了生活本身，更积极地生活了。",
      author: "阿柒",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 150
    },
    defaultStyle: {
      align: "left",
      backgroundName: "highlight-memo-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "24px",
      borderRadius: "0px",
      color: "#1f2937",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fbfbfb",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "zen-dark",
    name: "禅意黑",
    description: "极简暗黑风格，专注文字本身，静谧优雅",
    thumbnail: "zen-dark",
    defaultForm: {
      icon: "🧘",
      date: "2025年8月17日",
      title: "本周金句",
      content: "1. 关于运动：\n让时间变慢的方法就是投入进去。\n\n2. 关于精力充沛：\n睡前不要用脑，尽量做让身体愉悦的事情。\n\n3. 关于个人状态：\n保持觉知，保持可以随时抽离的状态。",
      author: "阿柒",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "生活日志",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 100
    },
    defaultStyle: {
      align: "left",
      backgroundName: "zen-dark-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "0px",
      color: "#e5e5e5",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#111111",
      containerRotate: 0,
      lineHeights: { content: "2" },
      letterSpacings: { content: "0.05em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "soft-pastel",
    name: "柔光",
    description: "柔和的渐变背景，搭配玻璃拟态，清新治愈",
    thumbnail: "soft-pastel",
    defaultForm: {
      icon: "☂️",
      date: "2025年8月15日",
      title: "物怪：唐伞",
      content: "《物怪：唐伞》篇章中，作为贯穿全系列的驱魔逻辑，卖药郎必须获得“形、真、理”三者，才能拔剑斩妖。每一案中的“形、真、理”都与事件本身、角色心理、社会背景紧密相连。",
      author: "唐伞",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 120
    },
    defaultStyle: {
      align: "center",
      backgroundName: "soft-pastel-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "12px",
      color: "#1e293b",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#e0f2fe",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "space-day",
    name: "太空日历",
    description: "极简暗黑日历风格，强调日期与核心观点",
    thumbnail: "space-day",
    defaultForm: {
      icon: "🪐",
      date: "2025-08-04",
      title: "论文=拼好文",
      content: "Space",
      author: "Space",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 10
    },
    defaultStyle: {
      align: "center",
      backgroundName: "space-day-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "0px",
      color: "#d4d4d4",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#1c1c1c",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "0.05em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "academic-classic",
    name: "经典学术",
    description: "深色纹理背景，适合经典著作摘录和深度阅读",
    thumbnail: "academic-classic",
    defaultForm: {
      icon: "📖",
      date: "2025/8/5",
      title: "《孟子》第4讲《梁惠王上之仁者无敌》",
      content: "仁者无敌，不是不杀，是为民，为了全民而处理“兽”。\n\n【遗姐收藏夹】解锁百位大V的认知内参",
      author: "卢麒元",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "立刻扫码入圈查阅全文 👉",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 100
    },
    defaultStyle: {
      align: "left",
      backgroundName: "academic-classic-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "0px",
      color: "#d4d4d8",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#18181b",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.02em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "blue-note",
    name: "蓝调笔记",
    description: "清新蓝调渐变，现代简约风格，适合日常记录",
    thumbnail: "blue-note",
    defaultForm: {
      icon: "💎",
      date: "2025年7月30日",
      title: "汗水滴在奋斗路上的声音",
      content: "💡 **汗水滴在奋斗路上的声音，和银行卡到账提示音很像，现在磨破的嘴皮，都是未来的财富密码。**",
      author: "生财青年俱乐部",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 60
    },
    defaultStyle: {
      align: "center",
      backgroundName: "blue-note-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.1,
      padding: "32px",
      borderRadius: "24px",
      color: "#1f2937",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "linear-gradient(135deg, #06b6d4 0%, #2563eb 100%)",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: false,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "literature-note",
    name: "文艺手札",
    description: "极简留白，衬线字体，适合长文摘录与诗歌",
    thumbnail: "literature-note",
    defaultForm: {
      icon: "🌿",
      date: "2025.07.09",
      title: "《我的母亲》",
      content: "坟头上的草青了又黄，黄了又青，就像我的念想一样，一年年总也断不了。\n\n我已经当了爸爸，也已经当了爷爷，但我已经三十多年没叫过妈妈了。我想着哪天我扛不动水泥了，就回村里换着那堆土躺下，没准那时候我再叫妈妈，她就能听见了。",
      author: "摘于抖音",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 120
    },
    defaultStyle: {
      align: "justify",
      backgroundName: "literature-note-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Songti SC",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "40px",
      borderRadius: "12px",
      color: "#333333",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "2" },
      letterSpacings: { content: "0.05em" },
      rowSpacings: { content: "24px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "handwritten-paper",
    name: "手写信纸",
    description: "暖色信纸背景，手写字体风格，充满温度",
    thumbnail: "handwritten-paper",
    defaultForm: {
      icon: "🐱",
      date: "2025年7月2日",
      title: "我训 AI 的一天",
      content: "1. 能干就干，不能干滚蛋。你不干，有的是 AI 干。\n\n2. 连个灵感都想不明白，你确定你是 AI ？\n\n3. 别急着回答，先看看你上次错成什么样。",
      author: "梁适之",
      textCount: "字数",
      qrCodeTitle: "流光卡片",
      qrCodeText: "",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 80
    },
    defaultStyle: {
      align: "left",
      backgroundName: "handwritten-paper-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "KaiTi",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1.1,
      padding: "32px",
      borderRadius: "16px",
      color: "#4b5563",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fdfbf7",
      containerRotate: 0,
      lineHeights: { content: "2.2" },
      letterSpacings: { content: "0.1em" },
      rowSpacings: { content: "20px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "bold-motivation",
    name: "醒目格言",
    description: "暗黑背景搭配高亮渐变文字，极具视觉冲击力",
    thumbnail: "bold-motivation",
    defaultForm: {
      icon: "🔥",
      date: "2025.08.20",
      title: "每日一言",
      content: "“\n\n**谋事不求易成，**\n\n**具备强烈的成功动机**",
      author: "Ant Card",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "Scan Me",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 20
    },
    defaultStyle: {
      align: "center",
      backgroundName: "bold-motivation-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Bold",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.2,
      padding: "32px",
      borderRadius: "24px",
      color: "#ffffff",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#111111",
      containerRotate: 0,
      lineHeights: { content: "1.5" },
      letterSpacings: { content: "0.02em" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: false,
      showDate: false,
      showTitle: false,
      showContent: true,
      showAuthor: false,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "polaroid-classic",
    name: "拍立得经典",
    description: "经典拍立得风格，上方图片下方留白，复古文艺",
    thumbnail: "polaroid-classic",
    defaultForm: {
      icon: "📸",
      date: "2025.08.25",
      title: "庞氏骗局都在骗谁",
      content: "很多东西说出来，就是旁氏骗局，只不过大家都是自欺欺人，都觉得，旁氏骗局倒台的那一天，自己已经抽身而去了。",
      author: "不止极客 | noGeek",
      textCount: "字数",
      qrCodeTitle: "Scan to read",
      qrCodeText: "",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 60
    },
    defaultStyle: {
      align: "left",
      backgroundName: "polaroid-classic-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "0px",
      borderRadius: "0px",
      color: "#4b5563",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "0.02em" },
      rowSpacings: { content: "16px" },
      backgroundImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1000&auto=format&fit=crop"
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: true,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "nature-morning",
    name: "清晨微语",
    description: "全屏自然风景背景，清新治愈，适合早安问候",
    thumbnail: "nature-morning",
    defaultForm: {
      icon: "☀️",
      date: "2025年6月9日 | 星期一",
      title: "每日微语",
      content: "想做的事，现在就开始行动吧，不必等万事俱备，不必追求完美无缺，行动本身就是治愈焦虑的良药。为眼前的每一分每一秒去努力，专注内心的丰盈，把握当下的幸福，才能拥有美好的未来。\n\n新的一天，早安！",
      author: "园区总工会",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "Scan Me",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 100
    },
    defaultStyle: {
      align: "left",
      backgroundName: "nature-morning-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "16px",
      color: "#ffffff",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#000000",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.05em" },
      rowSpacings: { content: "24px" },
      backgroundImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=1000&auto=format&fit=crop"
    },
    defaultSwitchConfig: {
      showIcon: false,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "mobile-note",
    name: "手机备忘",
    description: "模拟手机备忘录界面，生活化记录风格",
    thumbnail: "mobile-note",
    defaultForm: {
      icon: "📝",
      date: "2025年6月10日",
      title: "记住这10条美缝不翻车",
      content: "1. **美缝类型问题**：美缝就两类环氧美缝剂和聚脲美缝剂（原料区别）；环氧美缝剂材料更成熟可靠，聚脲美缝剂存在脱落与致敏问题。\n\n2. **彩砂与真瓷问题**：主要区别是否掺入细砂，没细砂的质感光亮属真瓷（适合抛光砖）。",
      author: "备忘录",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "Scan Me",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 150
    },
    defaultStyle: {
      align: "left",
      backgroundName: "mobile-note-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "0px",
      borderRadius: "24px",
      color: "#374151",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "1.7" },
      letterSpacings: { content: "0.02em" },
      rowSpacings: { content: "20px" }
    },
    defaultSwitchConfig: {
      showIcon: false,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: false,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  }
];

export const GITHUB_REPO_URL = "https://github.com/rpeng666/antcard";

export const PDF_EXPORT_CONFIG = {
  SERVER_URL:
    "https://1255612844-0z3iovadu8.ap-chengdu.tencentscf.com/generate-pdf",
  TIMEOUT: 30000, // 30秒超时
  MAX_RETRY: 3 // 最大重试次数
} as const;
