import { BasicFieldType } from "@/types/resume";
import { CardTemplate } from "@/types/template";

// 预设宽高比配置
export const ASPECT_RATIOS = [
  { id: "1:1", name: "1:1 正方形", ratio: 1, width: 400, height: 400 },
  { id: "3:4", name: "3:4 小红书", ratio: 3/4, width: 360, height: 480 },
  { id: "4:3", name: "4:3 Instagram", ratio: 4/3, width: 480, height: 360 },
  { id: "7:5", name: "7:5 Pinterest", ratio: 7/5, width: 420, height: 300 },
  { id: "9:16", name: "9:16 TikTok", ratio: 9/16, width: 270, height: 480 },
  { id: "16:9", name: "16:9 YouTube", ratio: 16/9, width: 480, height: 270 },
  { id: "210:297", name: "210:297 A4", ratio: 210/297, width: 350, height: 495 },
  { id: "custom", name: "自定义", ratio: 0, width: 440, height: 0 }
] as const;

export const DEFAULT_FIELD_ORDER: BasicFieldType[] = [
  { id: "1", key: "name", label: "姓名", type: "text", visible: true },

  { id: "2", key: "title", label: "职位", type: "text", visible: true },
  {
    id: "3",
    key: "employementStatus",
    label: "状态",
    type: "text",
    visible: true
  },
  { id: "4", key: "birthDate", label: "生日", type: "date", visible: true },
  { id: "5", key: "email", label: "邮箱", type: "text", visible: true },
  { id: "6", key: "phone", label: "电话", type: "text", visible: true },
  { id: "7", key: "location", label: "所在地", type: "text", visible: true }
];

export const DEFAULT_TEMPLATES: CardTemplate[] = [
  {
    id: "default",
    name: "默认",
    description: "简洁大方的默认卡片样式，适合各种内容展示",
    thumbnail: "default",
    defaultForm: {
      icon: "🚲",
      date: "2025年10月12日",
      title: "👋 hi 你好",
      content: "Product managers must have the ability to perceive human nature and business. Only in this way can they better identify market pain points, understand user needs, and use business to refine product ideas, instead of merely being an employee to implement the company's designated product roadmap.",
      author: "Ant Card",
      textCount: "Word count:",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 295
    },
    defaultStyle: {
      align: "left",
      backgroundName: "default-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "8px",
      color: "#212529",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "transparent",
    name: "透明",
    description: "透明背景设计，营造轻盈视觉效果",
    thumbnail: "transparent",
    defaultForm: {
      icon: "",
      date: "2025年10月12日",
      title: "透明卡片",
      content: "透明背景设计，营造轻盈的视觉效果，让内容更加突出。",
      author: "作者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 45
    },
    defaultStyle: {
      align: "left",
      backgroundName: "transparent-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "16px",
      color: "#374151",
      opacity: 1,
      blur: 10,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "rgba(248, 250, 252, 0.95)",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "quote",
    name: "金句",
    description: "引人注目的引述卡片设计，突出名言金句",
    thumbnail: "quote",
    defaultForm: {
      icon: "❝",
      date: "2025年10月12日",
      title: "每日金句",
      content: "生活就像骑自行车，想保持平衡就得往前走。",
      author: "阿尔伯特·爱因斯坦",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 21
    },
    defaultStyle: {
      align: "center",
      backgroundName: "quote-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.2,
      padding: "40px",
      borderRadius: "24px",
      color: "#1a202c",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)",
      containerRotate: -2,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.5px" },
      rowSpacings: { content: "16px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "book-excerpt",
    name: "书摘",
    description: "仿古书籍摘录设计，带有页边距和装订线效果",
    thumbnail: "book-excerpt",
    defaultForm: {
      icon: "📚",
      date: "2025年10月12日",
      title: "文学摘录",
      content: "读书是在别人思想的帮助下，建立起自己的思想。\n\n——鲁巴金",
      author: "摘录者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 28
    },
    defaultStyle: {
      align: "left",
      backgroundName: "book-excerpt-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Songti SC, serif",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1.1,
      padding: "40px 30px 40px 50px",
      borderRadius: "0px",
      color: "#333333",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f9f4e8",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.8px" },
      rowSpacings: { content: "12px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: true,
      showWatermark: false
    }
  },
  {
    id: "memo",
    name: "备忘录",
    description: "模仿iPhone备忘录设计，带有顶部导航栏和黄色主题",
    thumbnail: "memo",
    defaultForm: {
      icon: "📝",
      date: "2025年10月12日",
      title: "购物清单",
      content: "• 牛奶\n• 面包\n• 鸡蛋\n• 苹果\n• 洗发水",
      author: "备忘录",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 25
    },
    defaultStyle: {
      align: "left",
      backgroundName: "memo-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "0px",
      borderRadius: "12px",
      color: "#713f12",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fef3c7",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: false,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "bento",
    name: "便当",
    description: "真正的网格布局便当设计，信息分块展示",
    thumbnail: "bento",
    defaultForm: {
      icon: "🍱",
      date: "2025年10月12日",
      title: "信息便当",
      content: "## 今日要点\n- 项目进度更新\n- 团队会议安排\n- 客户反馈整理\n\n## 待办事项\n- [ ] 完成报告\n- [ ] 回复邮件\n- [ ] 准备演示",
      author: "便当师傅",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 45
    },
    defaultStyle: {
      align: "left",
      backgroundName: "bento-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "20px",
      borderRadius: "12px",
      color: "#1e293b",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f8fafc",
      containerRotate: 0,
      lineHeights: { content: "1.5" },
      letterSpacings: { content: "0.2px" },
      rowSpacings: { content: "8px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: false,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "dark-day",
    name: "黑日",
    description: "星空夜景设计，带有星光点缀效果",
    thumbnail: "dark-day",
    defaultForm: {
      icon: "✨",
      date: "2025年10月12日",
      title: "夜的诗篇",
      content: "夜空中的每一颗星，都是宇宙写给地球的情书。\n\n在这静谧的夜晚，让我们聆听内心的声音。",
      author: "观星者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 38
    },
    defaultStyle: {
      align: "center",
      backgroundName: "dark-day-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "9:16",
      height: 0,
      fontScale: 1.1,
      padding: "40px",
      borderRadius: "24px",
      color: "#f1f5f9",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "0.3px" },
      rowSpacings: { content: "16px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "frame",
    name: "框届",
    description: "艺术画框装饰设计，突出内容如艺术品般展示",
    thumbnail: "frame",
    defaultForm: {
      icon: "🎨",
      date: "2025年10月12日",
      title: "艺术之作",
      content: "每一个想法都是一件艺术品，\n每一句话都值得被精心装裱。\n\n在这个数字世界里，\n让文字回归艺术的本质。",
      author: "艺术家",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 42
    },
    defaultStyle: {
      align: "center",
      backgroundName: "frame-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "KaiTi, cursive",
      width: 440,
      ratio: "1:1",
      height: 0,
      fontScale: 1.1,
      padding: "50px 40px 50px 40px",
      borderRadius: "0px",
      color: "#2d3748",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fefefe",
      containerRotate: 0,
      lineHeights: { content: "2.0" },
      letterSpacings: { content: "1px" },
      rowSpacings: { content: "20px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "minimal",
    name: "简约",
    description: "极简主义设计，突出内容本质",
    thumbnail: "minimal",
    defaultForm: {
      icon: "",
      date: "2025年10月12日",
      title: "简约之美",
      content: "少即是多，简约不是简单，而是去除多余，保留精华。",
      author: "极简主义者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 28
    },
    defaultStyle: {
      align: "left",
      backgroundName: "minimal-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "40px",
      borderRadius: "4px",
      color: "#262626",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: false,
      showDate: false,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "story",
    name: "故事",
    description: "叙事风格设计，适合故事内容展示",
    thumbnail: "story",
    defaultForm: {
      icon: "📚",
      date: "2025年10月12日",
      title: "故事开始",
      content: "每个人都有自己的故事，每个故事都值得被倾听和记录。让我们一起分享这些美好的时光。",
      author: "故事讲述者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 44
    },
    defaultStyle: {
      align: "left",
      backgroundName: "story-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "36px",
      borderRadius: "12px",
      color: "#134e4a",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f0fdfa",
      containerRotate: 0,
      lineHeights: { content: "1.6" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: true,
      showWatermark: true
    }
  },
  {
    id: "handwritten",
    name: "手写",
    description: "手写风格设计，温馨个性化展示",
    thumbnail: "handwritten",
    defaultForm: {
      icon: "✍️",
      date: "2025年10月12日",
      title: "手写心情",
      content: "用心书写的文字总是带着温度，就像手写的信件一样，传递着真挚的情感。\n\n这是一段手写风格的文本示例，展现了手写模板的独特魅力。每一个字都仿佛带着书写者的温度，让阅读变得更加温暖和亲切。",
      author: "手写爱好者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 65
    },
    defaultStyle: {
      align: "left",
      backgroundName: "handwritten-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "'Kalam', cursive",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1.1,
      padding: "32px",
      borderRadius: "16px",
      color: "#831843",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)",
      containerRotate: 1,
      lineHeights: { content: "1.8" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: false,
      showQRCode: false,
      showPageNum: false,
      showWatermark: false
    }
  },
  {
    id: "code",
    name: "代码",
    description: "代码风格设计，适合技术内容展示",
    thumbnail: "code",
    defaultForm: {
      icon: "💻",
      date: "2025年10月12日",
      title: "代码人生",
      content: "// 人生就像写代码\n// 需要不断调试和优化\nconsole.log('Hello, World!');",
      author: "程序员",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 45
    },
    defaultStyle: {
      align: "left",
      backgroundName: "code-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "JetBrains Mono",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 0.9,
      padding: "24px",
      borderRadius: "8px",
      color: "#0f172a",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#f8fafc",
      containerRotate: 0,
      lineHeights: { content: "1.4" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "image",
    name: "图片",
    description: "图片展示优化设计，突出视觉内容",
    thumbnail: "image",
    defaultForm: {
      icon: "🖼️",
      date: "2025年10月12日",
      title: "视觉盛宴",
      content: "一图胜千言，好的视觉设计能够瞬间传达信息，触动人心。",
      author: "视觉设计师",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 30
    },
    defaultStyle: {
      align: "left",
      backgroundName: "image-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "32px",
      borderRadius: "12px",
      color: "#9a3412",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#fff7ed",
      containerRotate: 0,
      lineHeights: { content: "" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: false,
      showWatermark: true
    }
  },
  {
    id: "document",
    name: "文档",
    description: "简洁的白底 + 柔和阴影，给人「轻量」「清爽」「纸质笔记」的感觉",
    thumbnail: "document",
    defaultForm: {
      icon: "📄",
      date: "2025年10月12日",
      title: "文档标题",
      content: "## 二级标题\n\n这是文档内容区域，您可以在这里编写详细的内容。段落之间有充足的留白，让阅读体验更加舒适。\n\n### 三级标题\n\n- 列表项一\n- 列表项二\n- 列表项三\n\n```javascript\n// 示例代码\nconsole.log('Hello, World!');\n```\n\n> 这是一个引用区块，用于突出显示重要内容。",
      author: "作者",
      textCount: "字数",
      qrCodeTitle: "Ant Card",
      qrCodeText: "扫描二维码",
      pagination: "01",
      qrCode: "https://antcard.airouter.tech",
      textCountNum: 85
    },
    defaultStyle: {
      align: "left",
      backgroundName: "document-bg",
      backShadow: "",
      backShadowPositionX: 50,
      backShadowPositionY: 50,
      backShadowSize: 100,
      backShadowRotation: 0,
      font: "Alibaba-PuHuiTi-Regular",
      width: 440,
      ratio: "3:4",
      height: 0,
      fontScale: 1,
      padding: "40px",
      borderRadius: "8px",
      color: "#2d3748",
      opacity: 1,
      blur: 0,
      blurInset: "",
      backgroundAngle: "0deg",
      containerBg: "#ffffff",
      containerRotate: 0,
      lineHeights: { content: "1.7" },
      letterSpacings: { content: "" },
      rowSpacings: { content: "12px" }
    },
    defaultSwitchConfig: {
      showIcon: true,
      showDate: true,
      showTitle: true,
      showContent: true,
      showAuthor: true,
      showTextCount: true,
      showQRCode: true,
      showPageNum: true,
      showWatermark: false
    }
  }
];

export const GITHUB_REPO_URL = "https://github.com/rpeng666/antcard";

export const PDF_EXPORT_CONFIG = {
  SERVER_URL:
    "https://1255612844-0z3iovadu8.ap-chengdu.tencentscf.com/generate-pdf",
  TIMEOUT: 30000, // 30秒超时
  MAX_RETRY: 3 // 最大重试次数
} as const;
